version: '3.4'

services:
  postgresdb:
    image: postgres

  aspnetcore:
    image: ${DOCKER_REGISTRY-}aspnetcore
    build:
      context: .
      dockerfile: AspNetCore/Dockerfile

volumes:
  postgres_data: