version: '3.4'

services:
  postgresdb:
    image: postgres

  aspnetcore:
    image: ${DOCKER_REGISTRY-}aspnetcore
    build:
      context: .
      dockerfile: AspNetCore/Dockerfile

  pgadmin:
    image: dpage/pgadmin4

volumes:
  postgres_data:
  pgadmin_data: